services:

  app:
    build: .
    container_name: filestorage-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      JWT_SECRET: ${JWT_SECRET}
      DB_URL: jdbc:mysql://host.docker.internal:3306/saa?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      UPLOAD_DIR: /app/uploads
    volumes:
      - uploads_data:/app/uploads

volumes:
  mysql_data:
  uploads_data: