spring.application.name=FileStorage


#Configurando o multipart para os uploads dos arquivos
spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=5GB
spring.servlet.multipart.max-file-size=5GB
spring.servlet.multipart.max-request-size=5GB

#Caminho para salvar os arquivos na pasta

file.upload-dir=C:/Users/IPCOM/Documents/uploads
server.error.include-message=always