spring.application.name=FileStorage
api.security.token.secret=${JWT_SECRET:SecAgr1-key}

#Configurando o multipart para os uploads dos arquivos
spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=5GB
spring.servlet.multipart.max-file-size=5GB
spring.servlet.multipart.max-request-size=5GB

#Caminho para salvar os arquivos na pasta
#file.upload-dir=C:/Users/IPCOM/Documents/uploads
file.upload-dir=C:\\uploads
#file.upload-dir=D:\\guidr\\uploads
server.error.include-message=always
spring.datasource.schema=classpath:schema.sql

#H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:file:./uploads/dbfile;IFEXISTS=FALSE
#spring.datasource.url=jdbc:h2:file:D:/guidr/usuarios;IFEXISTS=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

#SPRING WEB
spring.web.encoding.charset=UTF-8
spring.web.encoding.enabled=true
spring.web.encoding.force=true

