spring.application.name=FileStorage


#Configurando o multipart para os uploads dos arquivos
spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=100MB
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=215MB

#Caminho para salvar os arquivos na pasta

file.upload-dir=D:/guidr/uploads
server.error.include-message=always